# Generated by Django 2.1.7 on 2019-05-18 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Project', max_length=100)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('D', 'Deleted'), ('N', 'Not active'), ('M', 'Merged to master'), ('T', 'Test')], default='N', max_length=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='New Story', max_length=100)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('D', 'Deleted'), ('N', 'Not active'), ('M', 'Merged to master'), ('T', 'Test')], default='N', max_length=1)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_story_user', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='story_owner', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='validator.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='Unnamed PR', max_length=100)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('D', 'Deleted'), ('N', 'Not active'), ('M', 'Merged to master'), ('T', 'Test')], default='N', max_length=1)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_task_user', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pr_creator', to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository', to='validator.Story')),
            ],
        ),
    ]
