# Generated by Django 2.1.7 on 2019-05-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pr',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='pr',
            name='name',
            field=models.CharField(default='Unnamed PR', max_length=100),
        ),
        migrations.AddField(
            model_name='repository',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='name',
            field=models.CharField(default='Unnamed Repository', max_length=100),
        ),
    ]
